package com.aearost.items;

public enum Items {
	// Basic Items
	TEA_LEAF,
	TEA_PLANT,
	TEA_BASE,
	
	// Tea Bags
	GREEN_TEA_BAG,
	APPLE_CINNAMON_TEA_BAG,
	CHAMOMILE_TEA_BAG,
	CHOCOLATE_TEA_BAG,
	HONEY_ROSE_TEA_BAG,
	JASMINE_TEA_BAG,
	MATCHA_TEA_BAG,
	SUSPICIOUS_TEA_BAG,
	TULIP_TEA_BAG,
	T8_TEA_BAG,
	WHITE_DRAGON_TEA_BAG,
	WHITE_JADE_TEA_BAG,
	
	// Teas
	GREEN_TEA,
	APPLE_CINNAMON_TEA,
	CHAMOMILE_TEA,
	CHOCOLATE_TEA,
	HONEY_ROSE_TEA,
	JASMINE_TEA,
	MATCHA_TEA,
	SUSPICIOUS_TEA,
	TULIP_TEA,
	T8_TEA,
	WHITE_DRAGON_TEA,
	WHITE_JADE_TEA,
	
	// Other Drinks
	CACTUS_JUICE
}
